lang:
  prefix: "&r[&b&lUn&6&lseeable&r]"
  nonconsole: "%prefix &rYou need to be a &6&lplayer&r to do this."
  suggest: "%prefix Please use $1."
  mapnotfound: "%prefix Map '$1' could not be found. Do /us list"
  mapinuse: "%prefix Map '$1' already exists."
  validnumber: "%prefix $1 needs to be a valid number."
  lesstwo: "%prefix $1 cannot be less than 2."
  selectwe: "%prefix Please select something using WorldEdit."
  cuboidwe: "%prefix Worth a try but selections need to be cuboid."
  mapcreate: "%prefix Successfully created map '$1'!"
  spawnadd: "%prefix Point added to map '$1' (currently $2)"
  spawnclear: "%prefix All points have been cleared for map '$1'"
  addorclear: "%prefix Please use 'add' or 'clear'"
  nomapsready: "%prefix &7No maps are ready to be played."
  mapnotsetup: "%prefix Map '$1' not setup properly."
  mapremove: "%prefix Successfully removed map '$1'."
  nogamestarted: "%prefix No game has started."
  gamealreadystopped: "%prefix Game already stopped."
  gamestopsuccess: "%prefix Game Stopped Successfully."
  startin: "%prefix Game Starting in $1 seconds."
  startinfast: "%prefix Game Starting in $1!"
  gamestart: "%prefix Game Started."
  spawn: "%prefix You have been spawned."
  fullroom: "%prefix Sorry, room is full."
  alreadyingame: "%prefix You are already ingame."
  queue: "%prefix Successfully joined the queue for '&a&l$1&r'."
  gamestillprogress: "%prefix Game still in progress."
  stop: "%prefix Game Abruptly Stopped. We are sorry for the inconvenience."
  chooseamap: "Choose a map ($1)"
  mapicon: "WOOL"
  maptitle: "&a&l$1"