name: Unseeable
version: 2.3-SNAPSHOT
main: nl.lucemans.unseeable.Unseeable
author: Lucemans
commands:
   unseeable:
     aliases: [us,unsee,uns]
     description: Unseeable main command
   unseeableadmin:
     aliases: [usa,unseeadmin,unsa]
     description: Unseeable main command