name: Unseeable
version: 3.9-SNAPSHOT
main: nl.lucemans.unseeable.Unseeable
author: Lucemans
commands:
   unseeable:
     aliases: [us,unsee,uns]
     description: Unseeable main command
     permission: unseeable.user
   unseeableadmin:
     aliases: [usa,unseeadmin,unsa]
     description: Unseeable main command
     permission: unseeable.admin